#!/usr/bin/env node
'use strict';
/**
 * apply-strips.js — draw white compliance partition strips onto images
 * (standalone, D-020; own implementation, same model as the storybook:
 * a torn-edge white strip asset composited through each living-being
 * character's body, from the top of the head to the bottom of the feet).
 *
 * Strips live in placements.json next to book.json:
 *   { "<filename>.png": [ { "x": 0.42, "y0": 0.05, "y1": 0.95, "strip": "auto" }, ... ] }
 *   x      : character midline as a fraction of image width
 *   y0, y1 : top of head / bottom of feet (fractions of height; default 0..1)
 *   strip  : "auto" (deterministic variant per file+x — reproducible re-runs)
 *            or an explicit "strip-a".."strip-d"
 * Files with no entry (or an empty list) are copied through untouched.
 * Up to 9 strips per image (crowd scenes).
 *
 * Assets come from strips/ (generated by make-strips.js; auto-generated on
 * first use). Chain: images-upscaled/ (strip-free masters) → images-compliant/.
 * Always re-applies from the master, so strips are editable, not cumulative.
 *
 * CLI:
 *   node src/tools/apply-strips.js --in <upscaled-dir> --out <compliant-dir>
 *        --placements <placements.json> [--file <one.png>] [--strips <dir>]
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { ensureStrips, VARIANTS, DEFAULT_STRIPS_DIR } = require('./make-strips');

// a multi-panel composite can hold a whole crowd (পাঠ ৯ has three panels of
// a boy plus a herd in one file), so this is a sanity bound, not a style rule
const MAX_STRIPS = 24;
// smallest believable head-to-feet span, as a fraction of image height
const MIN_SPAN = 0.02;
// The strip is sized from the figure it crosses, which collapses to 1-2px for
// a small animal in a panel — invisible on line art, and it partitions
// nothing. Floor it against the image width so every strip actually reads.
const MIN_WIDTH_FRAC = 0.0035;
// A strip has to contrast with the art it crosses: white through colour
// artwork, dark through black-and-white line art (where white would only
// erase ink and vanish across white clothing). Each gets a contrasting torn
// fringe so the edge reads either way.
const EDGE_PX = 3;
const INK = {
  white: { core: '#FFFFFF', edge: '#4a4a4a' },
  black: { core: '#1f1f1f', edge: '#FFFFFF' },
};
// A white strip is invisible on ground this light; use dark ink instead.
const PALE_LUMA_MIN = 200;

/**
 * Choose the ink from what the strips actually cross, not from the whole
 * picture. Whole-image colourfulness is a poor guide — a muted illustration
 * and white line art score alike — whereas the pixels under a strip answer
 * the real question: would a white strip be visible here? Decided once per
 * file so one image never mixes inks; a strip may still set s.ink itself.
 */
async function detectInk(src, strips, width, height) {
  const sharp = require('sharp');
  let sum = 0, count = 0;
  for (const s of strips) {
    const y0 = Math.max(0, s.y0 != null ? s.y0 : 0);
    const y1 = Math.min(1, s.y1 != null ? s.y1 : 1);
    const w = Math.max(2, Math.round(width * 0.02));               // sample a band, not a hairline
    const left = Math.max(0, Math.min(width - w, Math.round(s.x * width - w / 2)));
    const top = Math.max(0, Math.round(height * y0));
    const h = Math.max(1, Math.min(height - top, Math.round(height * (y1 - y0))));
    const { data, info } = await sharp(src)
      .extract({ left, top, width: w, height: h }).removeAlpha().raw()
      .toBuffer({ resolveWithObject: true });
    const n = info.width * info.height;
    for (let i = 0; i < n; i++) {
      // luma of the ground the strip covers
      sum += 0.299 * data[i * 3] + 0.587 * data[i * 3 + 1] + 0.114 * data[i * 3 + 2];
      count++;
    }
  }
  if (!count) return 'white';
  return (sum / count) > PALE_LUMA_MIN ? 'black' : 'white';
}

/** Recolour the torn strip shape, keeping its alpha. */
async function tintStrip(asset, w, h, colour) {
  const sharp = require('sharp');
  const shaped = await sharp(asset)
    .resize({ height: h, width: w, fit: 'fill', kernel: 'lanczos3' }).ensureAlpha().png().toBuffer();
  return sharp(shaped)
    .composite([{ input: { create: { width: w, height: h, channels: 4, background: colour } }, blend: 'in' }])
    .png().toBuffer();
}

function loadPlacements(p) {
  if (!fs.existsSync(p)) return {};
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// deterministic "auto" variant per filename+x — byte-reproducible re-runs
function pickVariant(filename, x) {
  const h = crypto.createHash('md5').update(filename + String(Math.round(x * 100))).digest();
  return VARIANTS[h.readUInt32BE(0) % VARIANTS.length].name;
}

/** Apply strips for one file from inDir master to outDir. Returns strip count. */
async function applyStripsToFile(file, inDir, outDir, placements, stripsDir) {
  const sharp = require('sharp');
  const src = path.join(inDir, file);
  if (!fs.existsSync(src)) throw new Error(`master image missing: ${src} (upscale stage must run first)`);
  fs.mkdirSync(outDir, { recursive: true });
  const dst = path.join(outDir, file);

  const raw = placements[file];
  const strips = (raw == null ? [] : (Array.isArray(raw) ? raw : [raw]))
    .filter(s => s && typeof s.x === 'number');
  if (!strips.length) {
    fs.copyFileSync(src, dst);
    return { count: 0, ink: null };
  }
  if (strips.length > MAX_STRIPS) throw new Error(`${file}: ${strips.length} strips > max ${MAX_STRIPS}`);

  stripsDir = await ensureStrips(stripsDir || DEFAULT_STRIPS_DIR);
  const img = sharp(src);
  const { width, height } = await img.metadata();
  // one detection per file; a strip may still override it with s.ink
  const fileInk = await detectInk(src, strips, width, height);

  const overlays = [];
  const inksUsed = new Set();
  for (const s of strips) {
    const name = (s.strip && s.strip !== 'auto') ? s.strip : pickVariant(file, s.x);
    const asset = path.join(stripsDir, `${name}.png`);
    if (!fs.existsSync(asset)) throw new Error(`strip asset not found: ${asset} (run make-strips.js)`);
    const y0 = Math.max(0, s.y0 != null ? s.y0 : 0);
    const y1 = Math.min(1, s.y1 != null ? s.y1 : 1);
    // A degenerate span used to composite a 1px mark: the image then LOOKS
    // stripped (it has a placement) while carrying nothing. Fail loudly.
    if (y1 - y0 < MIN_SPAN) {
      throw new Error(
        `${file}: strip at x=${s.x} spans ${(y1 - y0).toFixed(3)} of the height ` +
        `(min ${MIN_SPAN}) — re-place it: click 1 = top of head, click 2 = bottom of feet`
      );
    }
    const spanPx = Math.max(1, Math.round(height * (y1 - y0)));
    // scale by height (keeps the torn edge in proportion), then widen to the
    // floor if the figure is small — height stays as placed either way
    const natural = await sharp(asset).resize({ height: spanPx, kernel: 'lanczos3' })
      .png().toBuffer({ resolveWithObject: true });
    const minW = Math.round(width * MIN_WIDTH_FRAC);
    const { data, info } = natural.info.width >= minW ? natural
      : await sharp(asset).resize({ height: spanPx, width: minW, fit: 'fill', kernel: 'lanczos3' })
        .png().toBuffer({ resolveWithObject: true });
    // A pure white strip is invisible over white line art — it only shows
    // where it erases ink, so it vanishes across a white kurta. Use the ink
    // that contrasts with this artwork, and draw the same torn shape slightly
    // larger behind it in the opposite tone: the fringe gives the strip its
    // own edge, so it partitions the figure whatever lies beneath.
    const inkName = s.ink && s.ink !== 'auto' ? s.ink : fileInk;
    inksUsed.add(inkName);
    const ink = INK[inkName] || INK.white;
    const ew = info.width + EDGE_PX * 2, eh = info.height + EDGE_PX * 2;
    const edge = await tintStrip(asset, ew, eh, ink.edge);
    const core = ink.core === '#FFFFFF' ? data
      : await tintStrip(asset, info.width, info.height, ink.core);

    const left = Math.max(0, Math.min(width - info.width, Math.round(s.x * width - info.width / 2)));
    const top = Math.round(height * y0);
    overlays.push({ input: edge, left: Math.max(0, left - EDGE_PX), top: Math.max(0, top - EDGE_PX) });
    overlays.push({ input: core, left, top });
  }
  await img.composite(overlays).png().toFile(dst);
  return { count: strips.length, ink: [...inksUsed].join('+') };
}

async function applyAll(inDir, outDir, placements, onlyFile, stripsDir) {
  const files = onlyFile
    ? [onlyFile]
    : fs.readdirSync(inDir).filter(f => f.toLowerCase().endsWith('.png'));
  const report = [];
  for (const f of files) {
    const r = await applyStripsToFile(f, inDir, outDir, placements, stripsDir);
    report.push({ file: f, strips: r.count, ink: r.ink });
  }
  return report;
}

module.exports = { applyStripsToFile, applyAll, loadPlacements, pickVariant, MAX_STRIPS };

/* ---------- CLI ---------- */
if (require.main === module) {
  const rest = process.argv.slice(2);
  const opt = {};
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === '--in') opt.in = rest[++i];
    else if (rest[i] === '--out') opt.out = rest[++i];
    else if (rest[i] === '--placements') opt.placements = rest[++i];
    else if (rest[i] === '--file') opt.file = rest[++i];
    else if (rest[i] === '--strips') opt.strips = rest[++i];
  }
  if (!opt.in || !opt.out || !opt.placements) {
    console.error('usage: node src/tools/apply-strips.js --in <dir> --out <dir> --placements <json> [--file <one.png>] [--strips <dir>]');
    process.exit(2);
  }
  applyAll(path.resolve(opt.in), path.resolve(opt.out), loadPlacements(path.resolve(opt.placements)),
    opt.file, opt.strips && path.resolve(opt.strips))
    .then(rep => {
      for (const r of rep) console.log(`${r.file}: ${r.strips ? r.strips + ' strip(s) [' + r.ink + ' ink]' : 'pass-through'}`);
    })
    .catch(err => { console.error(`apply-strips: ${err.message}`); process.exit(1); });
}
